import type { AnalyzedEntity, AnalyzedField } from "./analyze.js";

function fieldTypeString(field: AnalyzedField): string {
  if (field.nullable) {
    return `${field.tsType} | null`;
  }
  return field.tsType;
}

function indent(text: string, level: number): string {
  const spaces = "  ".repeat(level);
  return text
    .split("\n")
    .map((line) => (line.trim() ? spaces + line : line))
    .join("\n");
}

function generateEntityFieldsType(entity: AnalyzedEntity): string {
  const lines = entity.fields.map(
    (f) => `${f.name}: ${fieldTypeString(f)};`,
  );
  return lines.join("\n");
}

function generateEntityRelationsType(entity: AnalyzedEntity): string {
  if (entity.relations.length === 0) return "";
  const lines = entity.relations.map(
    (r) =>
      `${r.fieldName}: { type: '${r.type}'; entity: '${r.targetEntityKey}' };`,
  );
  return lines.join("\n");
}

function generateCreateInputType(entity: AnalyzedEntity): string {
  const lines: string[] = [];

  for (const field of entity.fields) {
    if (field.name === "id" || field.name === "integer_id") continue;
    if (field.name === "created_at" || field.name === "updated_at") continue;
    lines.push(`${field.name}?: ${fieldTypeString(field)};`);
  }

  for (const rel of entity.relations) {
    for (const suffix of rel.suffixes) {
      lines.push(
        `${rel.fieldName}${suffix}?: Record<string, unknown>;`,
      );
    }
  }

  return lines.join("\n");
}

function generateUpdateInputType(entity: AnalyzedEntity): string {
  const lines: string[] = [];

  lines.push("id?: string;");
  lines.push(
    "__search_value?: { field: string; value?: string; not_found_behavior?: 'create' | 'skip' | 'error'; search_in_all_field_variants?: boolean; multiple_results_allowed?: boolean; multiple_results_use_latest?: boolean };",
  );

  for (const field of entity.fields) {
    if (field.name === "id" || field.name === "integer_id") continue;
    if (field.name === "created_at" || field.name === "updated_at") continue;
    lines.push(`${field.name}?: ${fieldTypeString(field)};`);
  }

  for (const rel of entity.relations) {
    for (const suffix of rel.suffixes) {
      lines.push(
        `${rel.fieldName}${suffix}?: Record<string, unknown>;`,
      );
    }
  }

  return lines.join("\n");
}

export function generateIndexFile(entities: AnalyzedEntity[], importSource: string): string {
  const lines: string[] = [];

  lines.push(
    "// Auto-generated by @pylo/core codegen — DO NOT EDIT",
    "",
    "export type {",
    "  FilterInput,",
    "  PaginationData,",
    "  PaginationInput,",
    "  QueryInput,",
    "  QueryInputCondition,",
    "  QueryOperator,",
    "  SortInput,",
    "  SortOrder,",
    "  SearchValueInput,",
    "  SchemaMetadata,",
    "  EntityMetadata,",
    `} from '${importSource}';`,
    "",
  );

  // Generate create/update input types for each entity
  for (const entity of entities) {
    lines.push(`export interface Create${entity.pascalName}Input {`);
    lines.push(indent(generateCreateInputType(entity), 1));
    lines.push("}", "");

    lines.push(`export interface Update${entity.pascalName}Input {`);
    lines.push(indent(generateUpdateInputType(entity), 1));
    lines.push("}", "");
  }

  // Generate PyloSchema
  lines.push("export interface PyloSchema {");
  for (const entity of entities) {
    lines.push(`  ${entity.key}: {`);
    lines.push("    fields: {");
    lines.push(indent(generateEntityFieldsType(entity), 3));
    lines.push("    };");

    const relType = generateEntityRelationsType(entity);
    lines.push("    relations: {");
    if (relType) {
      lines.push(indent(relType, 3));
    }
    lines.push("    };");

    lines.push(`    createInput: Create${entity.pascalName}Input;`);
    lines.push(`    updateInput: Update${entity.pascalName}Input;`);
    lines.push("  };");
  }
  lines.push("}", "");

  return lines.join("\n");
}

export function generateEntitiesFile(entities: AnalyzedEntity[], importSource: string): string {
  const lines: string[] = [];

  lines.push(
    "// Auto-generated by @pylo/core codegen — DO NOT EDIT",
    "",
    `import type { PaginationData } from '${importSource}';`,
    "",
  );

  for (const entity of entities) {
    lines.push(`export interface ${entity.pascalName} {`);
    for (const field of entity.fields) {
      lines.push(`  ${field.name}: ${fieldTypeString(field)};`);
    }
    for (const rel of entity.relations) {
      if (rel.type === "hasOne") {
        lines.push(`  ${rel.fieldName}?: { data: ${rel.targetEntityPascalName} } | null;`);
      } else {
        lines.push(`  ${rel.fieldName}?: { data: ${rel.targetEntityPascalName}[]; pagination: PaginationData };`);
      }
    }
    lines.push("}", "");
  }

  return lines.join("\n");
}

export function generateSchemaMetadataFile(
  entities: AnalyzedEntity[],
  unknownFieldBehavior: "error" | "ignore",
  importSource: string,
): string {
  const lines: string[] = [];

  lines.push(
    "// Auto-generated by @pylo/core codegen — DO NOT EDIT",
    "",
    `import type { SchemaMetadata } from '${importSource}';`,
    "",
    "export const schemaMetadata: SchemaMetadata = {",
    `  unknownFieldBehavior: '${unknownFieldBehavior}',`,
    "  entities: {",
  );

  for (const entity of entities) {
    lines.push(`    ${entity.key}: {`);
    lines.push(`      pascalName: '${entity.pascalName}',`);

    const scalarNames = entity.fields.map((f) => `'${f.name}'`).join(", ");
    lines.push(`      scalarFieldNames: [${scalarNames}],`);

    lines.push("      relations: {");
    for (const rel of entity.relations) {
      lines.push(
        `        ${rel.fieldName}: { type: '${rel.type}', entity: '${rel.targetEntityKey}', pascalName: '${rel.targetEntityPascalName}' },`,
      );
    }
    lines.push("      },");
    lines.push("    },");
  }

  lines.push("  },", "};", "");

  return lines.join("\n");
}
